//ONLY ADMIN
export const GET_ALL_USER_SUCCESS= 'GET_ALL_USER_SUCCESS';
export const CHANGE_ROLE__SUCCESS= 'CHANGE_ROLE__SUCCESS';
export const DELETE_USER_SUCCESS= 'DELETE_USER_SUCCESS';


// USER

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_FAIL= 'API_CALL_FAIL';
export const GET_COINS_SUCCESS = 'GET_COINS_SUCCESS';
export const AAD_FAV_SUCCESS= 'AAD_FAV_SUCCESS';
export const REMOVE_FAV_SUCCESS= 'REMOVE_FAV_SUCCESS';
export const GET_FAV_LIST_SUCCESS= 'GET_FAV_LIST_SUCCESS';

export const GET_USER_BEGIN = 'GET_USER_BEGIN';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL= 'GET_USER_FAIL';
export const LOGOUT_USER='LOGOUT_USER';
export const LOGIN_USER_BEGIN='LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCESS='LOGIN_USER_SUCESS';
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL';
export const SIGNIN_USER_BEGIN='SIGNIN_USER_BEGIN';
export const SIGNIN_USER_SUCESS='SIGNIN_USER_SUCESS';
export const SIGNIN_USER_FAIL='SIGNIN_USER_FAIL';
export const GET_ALL_POST_BEGIN='GET_ALL_POST_BEGIN';
export const GET_ALL_POST_SUCESS='GET_ALL_POST_SUCESS';
export const GET_ALL_POST_FAIL='GET_ALL_POST_FAIL';
export const GET_USER_POST_BEGIN='GET_USER_POST_BEGIN';
export const GET_USER_POST_SUCESS='GET_USER_POST_SUCESS';
export const GET_USER_POST_FAIL='GET_USER_POST_FAIL';
export const  DELETE_USER_POST='DELETE_USER_POST';